env {
  execution.parallelism = 2
  job.mode = "BATCH"
}

source {
  LocalFile {
    path = "/opt/airflow/data/raw/credit_scores.csv"
    file_format_type = "csv"
    skip_header_row_number = 1
    field_delimiter = ","
    schema = {
      fields {
        customer_id = string
        credit_score = int
        score_date = date
        credit_history_length = int
        number_of_accounts = int
        total_debt = double
        credit_utilization = double
      }
    }
    result_table_name = "raw_credit_scores"
  }
}

transform {
  Sql {
    source_table_name = "raw_credit_scores"
    result_table_name = "transformed_credit_scores"
    query = "SELECT *, CURRENT_TIMESTAMP AS ingestion_timestamp FROM raw_credit_scores"
  }
}

sink {
  Jdbc {
    source_table_name = "transformed_credit_scores"
    url = "jdbc:postgresql://postgres:5432/customer360_dw"
    driver = "org.postgresql.Driver"
    user = "postgres"
    password = "postgres"
    database = "customer360_dw"
    table = "staging.credit_scores"
    generate_sink_sql = true
  }
}
