env {
  execution.parallelism = 2
  job.mode = "BATCH"
}

source {
  LocalFile {
    path = "/opt/airflow/data/raw/customers.csv"
    file_format_type = "csv"
    skip_header_row_number = 1
    field_delimiter = ","
    schema = {
      fields {
        customer_id = string
        name = string
        date_of_birth = date
        address = string
        city = string
        state = string
        zip_code = string
        phone = string
        email = string
        annual_income = double
        job_title = string
        employment_status = string
        marital_status = string
        created_date = date
      }
    }
    result_table_name = "raw_customers"
  }
}

transform {
  Sql {
    source_table_name = "raw_customers"
    result_table_name = "transformed_customers"
    query = "SELECT *, CURRENT_TIMESTAMP AS ingestion_timestamp FROM raw_customers"
  }
}

sink {
  Jdbc {
    source_table_name = "transformed_customers"
    url = "jdbc:postgresql://postgres:5432/customer360_dw"
    driver = "org.postgresql.Driver"
    user = "postgres"
    password = "postgres"
    database = "customer360_dw"
    table = "staging.customers"
    primary_keys = ["customer_id"]
    generate_sink_sql = true
  }
}
